server.port=3200

spring.datasource.url=jdbc:mariadb://localhost:3306/wms_db
spring.datasource.username=testuser
spring.datasource.password=1234
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

jwt.secret=wms_bootcamp_jwt_secret_key_123456789_wms_project_2026
jwt.expiration=3600000
